services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wazum\Sluggi\:
    resource: '../Classes/*'

  Wazum\Sluggi\Backend\Hook\DataHandlerSlugUpdateHook:
    public: true
  Wazum\Sluggi\Backend\Hook\DatamapHook:
    public: true